// Single source of truth for the CLI version is cli/package.json. This writes
// it into src/version.ts so both build paths pick it up the same way:
//   - tsc (npm install path) compiles version.ts into dist/
//   - bun --compile (standalone-binary path) inlines the constant
// The generated file is git-ignored and (re)written by the pre* npm scripts.
import { readFileSync, writeFileSync } from "node:fs";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";

const cliRoot = join(dirname(fileURLToPath(import.meta.url)), "..");
const { version } = JSON.parse(
  readFileSync(join(cliRoot, "package.json"), "utf8"),
);

const out = join(cliRoot, "src", "version.ts");
const banner =
  "// GENERATED by scripts/gen-version.mjs from package.json — do not edit.\n";
writeFileSync(
  out,
  `${banner}export const VERSION = ${JSON.stringify(version)};\n`,
);
process.stdout.write(`gen-version: VERSION = ${version}\n`);
